
create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  created_at timestamptz not null default now()
);

create table public.customers (
  id text primary key,
  name text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create table public.services (
  id text primary key,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  type text not null check (type in ('per piece', 'per kg')),
  created_at timestamptz not null default now()
);

create table public.orders (
  id text primary key,
  token_no integer unique not null,
  customer_id text not null references public.customers(id),
  date date not null,
  delivery_date date not null,
  status text not null check (status in ('Received', 'Ready', 'Delivered')),
  total numeric(10,2) not null check (total >= 0),
  discount numeric(10,2) not null default 0 check (discount >= 0),
  paid numeric(10,2) not null default 0 check (paid >= 0),
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  service_id text not null references public.services(id),
  qty numeric(10,2) not null check (qty > 0),
  rate numeric(10,2) not null check (rate >= 0),
  amount numeric(10,2) not null check (amount >= 0)
);

create table public.inventory (
  id text primary key,
  name text not null,
  stock numeric(10,2) not null check (stock >= 0),
  unit text not null,
  min_stock numeric(10,2) not null check (min_stock >= 0),
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.customers enable row level security;
alter table public.services enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory enable row level security;

-- The Node server uses the Supabase service-role key for these operations.
-- It must never be exposed in browser code.
create policy "authenticated users can read users" on public.users for select to authenticated using (true);
create policy "authenticated users can read customers" on public.customers for select to authenticated using (true);
create policy "authenticated users can read services" on public.services for select to authenticated using (true);
create policy "authenticated users can read orders" on public.orders for select to authenticated using (true);
create policy "authenticated users can read order items" on public.order_items for select to authenticated using (true);
create policy "authenticated users can read inventory" on public.inventory for select to authenticated using (true);

-- After creating the owner in Supabase Auth, replace the UUID below and run:
-- insert into public.users (id, username) values ('AUTH_USER_UUID', 'owner');