
-- Run the full script in the Supabase SQL Editor to install or update the schema.

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id text primary key,
  name text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id text primary key,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  type text not null check (type in ('per piece', 'per kg')),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  token_no integer unique not null,
  customer_id text not null references public.customers(id),
  date date not null,
  delivery_date date not null,
  status text not null check (status in ('Received', 'Ready', 'Delivered')),
  total numeric(10,2) not null check (total >= 0),
  discount numeric(10,2) not null default 0 check (discount >= 0),
  paid numeric(10,2) not null default 0 check (paid >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  service_id text not null references public.services(id),
  qty numeric(10,2) not null check (qty > 0),
  rate numeric(10,2) not null check (rate >= 0),
  amount numeric(10,2) not null check (amount >= 0)
);

create table if not exists public.inventory (
  id text primary key,
  name text not null,
  stock numeric(10,2) not null check (stock >= 0),
  unit text not null,
  min_stock numeric(10,2) not null check (min_stock >= 0),
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.customers enable row level security;
alter table public.services enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory enable row level security;

-- The Node server uses the Supabase service-role key for these operations.
-- It must never be exposed in browser code.
drop policy if exists "authenticated users can read users" on public.users;
drop policy if exists "authenticated users can read customers" on public.customers;
drop policy if exists "authenticated users can read services" on public.services;
drop policy if exists "authenticated users can read orders" on public.orders;
drop policy if exists "authenticated users can read order items" on public.order_items;
drop policy if exists "authenticated users can read inventory" on public.inventory;
create policy "authenticated users can read users" on public.users for select to authenticated using (true);
create policy "authenticated users can read customers" on public.customers for select to authenticated using (true);
create policy "authenticated users can read services" on public.services for select to authenticated using (true);
create policy "authenticated users can read orders" on public.orders for select to authenticated using (true);
create policy "authenticated users can read order items" on public.order_items for select to authenticated using (true);
create policy "authenticated users can read inventory" on public.inventory for select to authenticated using (true);

-- After creating the owner in Supabase Auth, replace the UUID below and run:
-- insert into public.users (id, username) values ('AUTH_USER_UUID', 'owner');

alter table public.inventory
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists last_updated_at timestamptz not null default now();
alter table public.inventory
  alter column stock type numeric(12,3) using stock::numeric(12,3),
  alter column min_stock type numeric(12,3) using min_stock::numeric(12,3);

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) > 0),
  contact_person text,
  phone text,
  email text,
  address text,
  registration_number text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.suppliers add column if not exists registration_number text;

create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  purchase_number text not null unique,
  supplier_id uuid not null references public.suppliers(id),
  purchase_date date not null default current_date,
  invoice_number text,
  total_amount numeric(12,2) not null check (total_amount >= 0),
  amount_paid numeric(12,2) not null default 0 check (amount_paid >= 0),
  balance_amount numeric(12,2) not null check (balance_amount >= 0),
  payment_status text not null check (payment_status in ('Paid', 'Unpaid', 'Partially Paid')),
  purchase_status text not null check (purchase_status in ('Draft', 'Ordered', 'Received', 'Cancelled')),
  notes text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (amount_paid <= total_amount),
  check (balance_amount = total_amount - amount_paid),
  check (
    (payment_status = 'Paid' and balance_amount = 0)
    or (payment_status = 'Unpaid' and amount_paid = 0 and balance_amount > 0)
    or (payment_status = 'Partially Paid' and amount_paid > 0 and balance_amount > 0)
  )
);

create table if not exists public.purchase_items (
  id uuid primary key default gen_random_uuid(),
  purchase_id uuid not null references public.purchases(id) on delete cascade,
  inventory_id text references public.inventory(id),
  item_name text,
  quantity numeric(12,3) not null check (quantity > 0),
  unit text not null check (length(trim(unit)) > 0),
  unit_cost numeric(12,2) not null check (unit_cost >= 0),
  total_amount numeric(12,2) not null check (total_amount >= 0),
  created_at timestamptz not null default now(),
  check (inventory_id is not null or length(trim(coalesce(item_name, ''))) > 0),
  check (total_amount = round(quantity * unit_cost, 2))
);

create table if not exists public.stock_transactions (
  id uuid primary key default gen_random_uuid(),
  inventory_id text not null references public.inventory(id),
  transaction_type text not null check (
    transaction_type in ('STOCK_IN', 'STOCK_OUT', 'PURCHASE', 'DAMAGE', 'EXPIRED', 'ADJUSTMENT')
  ),
  quantity_change numeric(12,3) not null check (quantity_change <> 0),
  previous_stock numeric(12,3) not null check (previous_stock >= 0),
  new_stock numeric(12,3) not null check (new_stock >= 0),
  supplier_id uuid references public.suppliers(id) on delete set null,
  purchase_id uuid references public.purchases(id) on delete set null,
  transaction_date timestamptz not null default now(),
  notes text,
  created_by uuid references public.users(id) on delete set null,
  check (new_stock = previous_stock + quantity_change)
);

alter table public.purchase_items alter column inventory_id drop not null;

create index if not exists purchases_supplier_date_idx
  on public.purchases (supplier_id, purchase_date desc);
create index if not exists purchases_status_date_idx
  on public.purchases (purchase_status, purchase_date desc);
create index if not exists purchase_items_purchase_idx
  on public.purchase_items (purchase_id);
create index if not exists stock_transactions_inventory_date_idx
  on public.stock_transactions (inventory_id, transaction_date desc);

alter table public.suppliers enable row level security;
alter table public.purchases enable row level security;
alter table public.purchase_items enable row level security;
alter table public.stock_transactions enable row level security;

drop policy if exists "authenticated users can read suppliers" on public.suppliers;
drop policy if exists "authenticated users can read purchases" on public.purchases;
drop policy if exists "authenticated users can read purchase items" on public.purchase_items;
drop policy if exists "authenticated users can read stock transactions" on public.stock_transactions;
create policy "authenticated users can read suppliers" on public.suppliers
  for select to authenticated using (true);
create policy "authenticated users can read purchases" on public.purchases
  for select to authenticated using (true);
create policy "authenticated users can read purchase items" on public.purchase_items
  for select to authenticated using (true);
create policy "authenticated users can read stock transactions" on public.stock_transactions
  for select to authenticated using (true);
grant select on public.suppliers, public.purchases, public.purchase_items,
  public.stock_transactions, public.inventory to authenticated;
revoke insert, update, delete on public.inventory from anon, authenticated;

create or replace function public.create_inventory_item(
  p_name text,
  p_stock numeric,
  p_unit text,
  p_min_stock numeric,
  p_created_by uuid
) returns public.inventory
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.inventory;
begin
  if length(trim(coalesce(p_name, ''))) = 0
    or length(trim(coalesce(p_unit, ''))) = 0
    or p_stock < 0 or p_min_stock < 0 then
    raise exception 'Inventory name, unit, and non-negative stock values are required';
  end if;

  insert into public.inventory (id, name, stock, unit, min_stock, updated_at, last_updated_at)
  values ('inv-' || gen_random_uuid()::text, trim(p_name), 0, trim(p_unit), p_min_stock, now(), now())
  returning * into v_item;

  if p_stock > 0 then
    update public.inventory
      set stock = p_stock, updated_at = now(), last_updated_at = now()
      where id = v_item.id
      returning * into v_item;
    insert into public.stock_transactions (
      inventory_id, transaction_type, quantity_change, previous_stock, new_stock,
      transaction_date, notes, created_by
    ) values (v_item.id, 'STOCK_IN', p_stock, 0, p_stock, now(), 'Opening stock', p_created_by);
  end if;
  return v_item;
end;
$$;

create or replace function public.create_purchase(
  p_supplier_id uuid,
  p_purchase_date date,
  p_invoice_number text,
  p_amount_paid numeric,
  p_purchase_status text,
  p_notes text,
  p_created_by uuid,
  p_items jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase_id uuid := gen_random_uuid();
  v_number text := 'PUR-' || to_char(current_date, 'YYYYMMDD') || '-' || upper(substr(gen_random_uuid()::text, 1, 8));
  v_line jsonb;
  v_inventory_id text;
  v_name text;
  v_quantity numeric;
  v_unit text;
  v_cost numeric;
  v_line_total numeric(12,2);
  v_total numeric(12,2) := 0;
  v_paid numeric(12,2);
  v_balance numeric(12,2);
  v_payment_status text;
begin
  if not exists (select 1 from public.suppliers where id = p_supplier_id and is_active) then
    raise exception 'Choose an active supplier';
  end if;
  if p_purchase_status not in ('Draft', 'Ordered') then
    raise exception 'New purchases must be Draft or Ordered';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'A purchase must contain at least one item';
  end if;

  insert into public.purchases (
    id, purchase_number, supplier_id, purchase_date, invoice_number, total_amount,
    amount_paid, balance_amount, payment_status, purchase_status, notes, created_by
  ) values (
    v_purchase_id, v_number, p_supplier_id, p_purchase_date, p_invoice_number, 0,
    0, 0, 'Paid', p_purchase_status, p_notes, p_created_by
  );

  for v_line in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := round((v_line->>'quantity')::numeric, 3);
    v_cost := round((v_line->>'unit_cost')::numeric, 2);
    v_unit := trim(coalesce(v_line->>'unit', ''));
    if v_quantity <= 0 or v_cost < 0 or v_unit = '' then
      raise exception 'Item quantity must be positive and unit cost non-negative';
    end if;
    v_inventory_id := nullif(v_line->>'inventory_id', '');
    v_name := nullif(trim(coalesce(v_line->>'item_name', '')), '');
    if v_inventory_id is null and v_name is null then
      raise exception 'New inventory items require a name';
    elsif v_inventory_id is not null then
      select name into v_name from public.inventory
        where id = v_inventory_id and unit = v_unit;
      if not found then raise exception 'Selected inventory item does not exist'; end if;
    end if;
    v_line_total := round(v_quantity * v_cost, 2);
    v_total := v_total + v_line_total;
    insert into public.purchase_items (
      purchase_id, inventory_id, item_name, quantity, unit, unit_cost, total_amount
    ) values (v_purchase_id, v_inventory_id, v_name, v_quantity, v_unit, v_cost, v_line_total);
  end loop;

  v_paid := round(p_amount_paid, 2);
  if v_paid < 0 or v_paid > v_total then
    raise exception 'Amount paid must be between zero and the purchase total';
  end if;
  v_balance := v_total - v_paid;
  v_payment_status := case
    when v_balance = 0 then 'Paid'
    when v_paid = 0 then 'Unpaid'
    else 'Partially Paid'
  end;
  update public.purchases
    set total_amount = v_total, amount_paid = v_paid, balance_amount = v_balance,
      payment_status = v_payment_status
    where id = v_purchase_id;
  return v_purchase_id;
end;
$$;

create or replace function public.receive_purchase(
  p_purchase_id uuid,
  p_created_by uuid
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase public.purchases;
  v_line record;
  v_inventory_id text;
  v_previous numeric(12,3);
  v_new numeric(12,3);
begin
  select * into v_purchase from public.purchases where id = p_purchase_id for update;
  if not found then raise exception 'Purchase not found'; end if;
  if v_purchase.purchase_status not in ('Draft', 'Ordered') then
    raise exception 'Only Draft or Ordered purchases can be received once';
  end if;
  if not exists (select 1 from public.purchase_items where purchase_id = p_purchase_id) then
    raise exception 'A purchase must contain at least one item';
  end if;

  for v_line in
    select pi.id as purchase_item_id, pi.inventory_id, pi.item_name, pi.quantity, pi.unit
    from public.purchase_items pi
    where pi.purchase_id = p_purchase_id
    order by pi.id
  loop
    v_inventory_id := v_line.inventory_id;
    if v_inventory_id is null then
      if length(trim(coalesce(v_line.item_name, ''))) = 0 then
        raise exception 'A new inventory item needs a name';
      end if;
      v_inventory_id := 'inv-' || gen_random_uuid()::text;
      insert into public.inventory (id, name, stock, unit, min_stock, updated_at, last_updated_at)
      values (v_inventory_id, v_line.item_name, 0, v_line.unit, 0, now(), now());
      update public.purchase_items set inventory_id = v_inventory_id
        where id = v_line.purchase_item_id;
    end if;
    select stock into v_previous from public.inventory where id = v_inventory_id for update;
    if not found then raise exception 'Inventory item no longer exists'; end if;
    v_new := v_previous + v_line.quantity;
    update public.inventory
      set stock = v_new, updated_at = now(), last_updated_at = now()
      where id = v_inventory_id;
    insert into public.stock_transactions (
      inventory_id, transaction_type, quantity_change, previous_stock, new_stock,
      supplier_id, purchase_id, transaction_date, notes, created_by
    ) values (
      v_inventory_id, 'PURCHASE', v_line.quantity, v_previous, v_new,
      v_purchase.supplier_id, p_purchase_id, now(), 'Received purchase ' || v_purchase.purchase_number, p_created_by
    );
  end loop;

  update public.purchases set purchase_status = 'Received', updated_at = now()
    where id = p_purchase_id;
  return jsonb_build_object('id', p_purchase_id, 'purchase_status', 'Received');
end;
$$;

create or replace function public.record_stock_transaction(
  p_inventory_id text,
  p_transaction_type text,
  p_quantity_change numeric,
  p_notes text,
  p_created_by uuid
) returns public.stock_transactions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous numeric(12,3);
  v_new numeric(12,3);
  v_transaction public.stock_transactions;
begin
  if p_transaction_type not in ('STOCK_IN', 'STOCK_OUT', 'DAMAGE', 'EXPIRED', 'ADJUSTMENT')
    or p_quantity_change = 0 then
    raise exception 'Invalid stock transaction';
  end if;
  if (p_transaction_type = 'STOCK_IN' and p_quantity_change < 0)
    or (p_transaction_type in ('STOCK_OUT', 'DAMAGE', 'EXPIRED') and p_quantity_change > 0) then
    raise exception 'Quantity sign does not match transaction type';
  end if;
  select stock into v_previous from public.inventory where id = p_inventory_id for update;
  if not found then raise exception 'Inventory item not found'; end if;
  v_new := v_previous + p_quantity_change;
  if v_new < 0 then raise exception 'Stock cannot become negative'; end if;
  update public.inventory set stock = v_new, updated_at = now(), last_updated_at = now()
    where id = p_inventory_id;
  insert into public.stock_transactions (
    inventory_id, transaction_type, quantity_change, previous_stock, new_stock,
    transaction_date, notes, created_by
  ) values (
    p_inventory_id, p_transaction_type, p_quantity_change, v_previous, v_new,
    now(), p_notes, p_created_by
  ) returning * into v_transaction;
  return v_transaction;
end;
$$;

revoke all on function public.create_inventory_item(text, numeric, text, numeric, uuid)
  from public, anon, authenticated;
revoke all on function public.create_purchase(uuid, date, text, numeric, text, text, uuid, jsonb)
  from public, anon, authenticated;
revoke all on function public.receive_purchase(uuid, uuid)
  from public, anon, authenticated;
revoke all on function public.record_stock_transaction(text, text, numeric, text, uuid)
  from public, anon, authenticated;
grant execute on function public.create_inventory_item(text, numeric, text, numeric, uuid)
  to service_role;
grant execute on function public.create_purchase(uuid, date, text, numeric, text, text, uuid, jsonb)
  to service_role;
grant execute on function public.receive_purchase(uuid, uuid)
  to service_role;
grant execute on function public.record_stock_transaction(text, text, numeric, text, uuid)
  to service_role;